version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=db_name
      - DB_USERNAME=db_user
      - DB_PASSWORD=User_password
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - laravel_network

  webserver:
    image: nginx:latest
    container_name: laravel_web
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: User_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  mysql_data:
